#!/bin/sh
#
# Pre-renders every SVG figure under results/ to a same-named PDF, so that
# paper.tex can be compiled with \finalsubmissiontrue (see the top of paper.tex)
# on systems without Inkscape and/or -shell-escape, such as most cloud/journal
# LaTeX services.
#
# Run this once before such a submission build, and again whenever results/
# has been regenerated by ft-db-exp2. Requires Inkscape on PATH.

set -eu

SCRIPT_DIR=$(cd "$(dirname "$0")" && pwd)
RESULTS_DIR="$SCRIPT_DIR/results"

if ! command -v inkscape >/dev/null 2>&1; then
    echo "Error: inkscape not found on PATH." >&2
    exit 1
fi

if [ ! -d "$RESULTS_DIR" ]; then
    echo "Error: $RESULTS_DIR not found." >&2
    exit 1
fi

count=0
for svg in "$RESULTS_DIR"/*.svg; do
    [ -e "$svg" ] || continue
    pdf="${svg%.svg}.pdf"
    echo "Converting $(basename "$svg") -> $(basename "$pdf")"
    inkscape "$svg" --export-type=pdf --export-filename="$pdf"
    count=$((count + 1))
done

if [ "$count" -eq 0 ]; then
    echo "No SVG files found in $RESULTS_DIR."
    exit 0
fi

echo "Done. $count file(s) converted."
